server:  port: 8000logging:  file:     path: C:/elk/vz_customer_service  level:    org.springframework.web: DEBUG    org.hibernate: DEBUG    com.verizon.customer: DEBUG  pattern:    level: "%d %-5level [%thread] %logger : %msg%n"spring:
  application:
    name: serviceCustomer
  profiles:    active:    - dev
  cloud:    config:      uri:      - http://localhost:8888/
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: trueeureka:  client:    register-with-eureka: true    fetch-registry: true    service-url:      defaultZone: http://localhost:8761/eureka/  instance:    hostname: localhost